import Head from 'next/head'
import { useEffect, useState } from 'react';
import SearchBar from '@/components/SearchBar';
// import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/product.module.css'
import Wrapper from '@/components/Wrapper/index'
import Image from 'next/image'
import martini from '@/public/images/martini.jpg'
import { useSelector, useDispatch } from 'react-redux';
import { add, remove } from '@/store/slices/cartSlice';
import payNow from '@/public/images/pay.svg'

export default function Home() {
  const [data, setData] = useState([]);
  const [totalAmount, setTotalAmount] = useState(0);

const dispatch =useDispatch()
const cart =useSelector(state=> state.cart)


useEffect(() => {
    setData(cart)
    let total =0
    cart.map((each)=>{
        total =total + each.price
    })
    setTotalAmount(total)
  }, [cart]);










  return (

    <>
      <Head>
        <title>Beerr Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Wrapper>
     <main className={styles.products} >
      <section className={styles.project_section}>
      <div className={styles.checkout} >        
        <h1 style={{textDecoration: 'underline'}}>Cart:</h1>
        <button  styles={{border: 'none'}}><Image src={payNow} alt='pay'/>Check out</button>

        </div>      
<div className={styles.total }><h3 >{`Total number : ${data.length}`}</h3>
    <h3>{`Total amount : ₦${totalAmount}`}</h3>
</div>

          <ul>
       
              {data.map((each)=>{

                return    <li key={each.id}>
                <Image src={`/images/${each.image}`} alt='product Image'  width={100} height={100}/>
                <div>
                  <h4>{each.name}</h4>
                  <span><b>₦</b><b>{each.price}</b></span>
                  <button style={{backgroundColor: cart?.find(obj => obj.id === each.id)? 'blue': '#cccaca'}}  onClick={(e) => {
                    dispatch(add(each))

                    if(cart?.find(obj => obj.id === each.id)){
                      dispatch(remove(each))                      
                    }else{
                      dispatch(add(each))
                    }
                    
                    }}>{cart?.find(obj => obj.id === each.id)?'Remove' : 'Add to cart'}</button>                </div>
              </li>
              })}
          </ul>
{data.length === 0 && <p className={styles.null_product}>No producted added yet</p>}
      
      </section>

      </main>
     </Wrapper>
    </>
  )
}
